### ISSUE TITLE
Unable to debug plugin when Start Debugging (F5) is done in visual studio

### ISSUE THREAD

**Issue by ginow** [NicolasPrats/DvBrowser#24]
Tried to attach a debugger on an update of contact plugin but it isn't showing me the list of visual studio instances. 

![image](https://github.com/NicolasPrats/DvBrowser/assets/15030674/705a64c1-0c4a-4713-ae91-1535718a8a51)

It asks for the instance only when .exe file is run from the bin folder
![image](https://github.com/NicolasPrats/DvBrowser/assets/15030674/43348508-a113-4303-988f-1cce3ff982b0)

Also while debugging the plugin when running from visual studio instead of .exe file I got below error:

![image](https://github.com/NicolasPrats/DvBrowser/assets/15030674/371c0ac4-4c0e-447c-a753-730ce9f87ae4)

**Comment by NicolasPrats** [comment]
Hi @ginow,

Thank you for opening this issue.

The behavior you described regarding the debuggers is as expected:

- If you start the DvBrowser using its source code from Visual Studio, then a debugger is automatically attached. Since only one debugger can be attached, clicking on the "debugger" button in the DvBrowser, will only inform you that a debugger is attached.
- If you start the DvBrowser from the .exe file, then no debugger is attached. In this case, when you click on the "debugger" button, you can choose which debugger will be attached.

Please note that for debugging your plugins, the second option is preferable. You should download the latestet release and directly  start the .exe file. Consider using the DvBrowser source code only if you want to contribute to it or analyze how it works.

Regarding the NotImplementedException on OwningExtension: it's a feature that your plugin is using but not implemented. Since you mentioned that your plugin is very simple, I assume you are using a specific framework and/or a plugin base class that is responsible of the call to the OwningExtension (may be for logging some information). You can verify that by looking at the call stack.
That said, it's a quite simple property, I can implement it for the next release.

**Comment by ginow** [comment]
Hi @NicolasPrats 

Thank you for the quick reply, understood it.
Also thanks for building this awesome tool!, eagerly looking forward for new features.

**Comment by NicolasPrats** [comment]
Thank you for your feedback!

The [new release](https://github.com/NicolasPrats/DvBrowser/releases/download/V1.0.2.0/Dataverse.Browser.V1.0.2.0.zip) includes the support of the OwningExtension.
I close this issue, feel free to open a new one if you have another problem.
